# Generated by Django 4.1.9 on 2023-06-04 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=20)),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('directory_name', models.CharField(max_length=20)),
                ('short_description', models.CharField(max_length=2000)),
                ('biography', models.CharField(max_length=20000)),
            ],
        ),
    ]
