# Generated by Django 4.1.9 on 2023-06-04 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whole_name', models.CharField(max_length=20)),
                ('background_color', models.CharField(max_length=15)),
                ('wiki_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TheMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('duration', models.CharField(max_length=10)),
                ('movie_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('MPAA_rating', models.CharField(max_length=10)),
                ('directory_name', models.CharField(max_length=20)),
                ('in_cinema', models.BooleanField()),
                ('on_tv', models.BooleanField()),
                ('genres', models.ManyToManyField(to='movies.moviegenre')),
            ],
        ),
    ]
